# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Users/trialley/Desktop/LS_CPU_LAB/6_single_cycle_cpu/6_single_cycle_cpu/6_single_cycle_cpu.cache/wt [current_project]
set_property parent.project_path D:/Users/trialley/Desktop/LS_CPU_LAB/6_single_cycle_cpu/6_single_cycle_cpu/6_single_cycle_cpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
add_files -quiet D:/Users/trialley/Desktop/LS_CPU_LAB/lcd_module.dcp
set_property used_in_implementation false [get_files D:/Users/trialley/Desktop/LS_CPU_LAB/lcd_module.dcp]
read_verilog -library xil_defaultlib {
  D:/Users/trialley/Desktop/LS_CPU_LAB/6_single_cycle_cpu/adder.v
  D:/Users/trialley/Desktop/LS_CPU_LAB/6_single_cycle_cpu/alu.v
  D:/Users/trialley/Desktop/LS_CPU_LAB/6_single_cycle_cpu/data_ram.v
  D:/Users/trialley/Desktop/LS_CPU_LAB/6_single_cycle_cpu/inst_rom.v
  D:/Users/trialley/Desktop/LS_CPU_LAB/6_single_cycle_cpu/regfile.v
  D:/Users/trialley/Desktop/LS_CPU_LAB/6_single_cycle_cpu/single_cycle_cpu.v
  D:/Users/trialley/Desktop/LS_CPU_LAB/6_single_cycle_cpu/single_cycle_cpu_display.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Users/trialley/Desktop/LS_CPU_LAB/6_single_cycle_cpu/single_cycle_cpu.xdc
set_property used_in_implementation false [get_files D:/Users/trialley/Desktop/LS_CPU_LAB/6_single_cycle_cpu/single_cycle_cpu.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top single_cycle_cpu_display -part xc7a200tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef single_cycle_cpu_display.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file single_cycle_cpu_display_utilization_synth.rpt -pb single_cycle_cpu_display_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
