webtalk_init -webtalk_dir D:/Users/12037/Desktop/Loongson cup/loongson_MIPS_demo/6pipeline_CU_cpu/6pipeline_CU_cpu.sim/sim_1/synth/func/xsim/xsim.dir/tb_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri May  3 10:26:35 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c8061d03-9984-46eb-b732-e4365f0d69e6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "247ceffa317b496f92d3106d2a321d11" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "0 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "21716_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3811850510 -regid "" -xml D:/Users/12037/Desktop/Loongson cup/loongson_MIPS_demo/6pipeline_CU_cpu/6pipeline_CU_cpu.sim/sim_1/synth/func/xsim/xsim.dir/tb_func_synth/webtalk/usage_statistics_ext_xsim.xml -html D:/Users/12037/Desktop/Loongson cup/loongson_MIPS_demo/6pipeline_CU_cpu/6pipeline_CU_cpu.sim/sim_1/synth/func/xsim/xsim.dir/tb_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm D:/Users/12037/Desktop/Loongson cup/loongson_MIPS_demo/6pipeline_CU_cpu/6pipeline_CU_cpu.sim/sim_1/synth/func/xsim/xsim.dir/tb_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
